### ISSUE TITLE
Missing return when Write is cancelled

### ISSUE THREAD

**Issue by lolgab** [tkp1n/IoUring#16]
Shouldn't you return [here](https://github.com/tkp1n/IoUring/blob/c4cf2ace039a387feec0e0c264ef85841440eb66/src/IoUring.Transport/Internals/TransportThread.cs#L225) ?
Then you are preparing to write on an already closed socket.

**Comment by tkp1n** [comment]
Good catch! Thank you for reporting this. Would you like to fix this in a PR? 

I‘m mostly offline this week and would otherwise fix it next week...
