### ISSUE TITLE
API suggestion: Completion.result use long instead of int

### ISSUE THREAD

**Issue by tmds** [tkp1n/IoUring#19]
Completion result is of type int.
```cs
public readonly int result;
```
Return values from the kernel match the machine size. For example `ssize_t` for `read` is a signed 64-bit nr on x64.

Can we change `result` to be a `long` to reflect this?

**Comment by tkp1n** [comment]
The `res` field of `io_uring_cqe` is of type `__s32`:
https://github.com/torvalds/linux/blob/b1da3acc781ce445445d959b41064d209a27bc2d/include/uapi/linux/io_uring.h#L136

`Completion` is just a _better-looking_ copy of `io_uring_cqe`.
Am I missing something?

**Comment by tmds** [comment]
> Am I missing something?

No. I didn't look at the struct. APIs I'm familiar with use a C-type `long` to carry `res`. Thanks for clarifying.
