### ISSUE TITLE
SubmissionQueueSize is not expected value

### ISSUE THREAD

**Issue by tmds** [tkp1n/IoUring#22]
`SubmissionQueueSize` for `new Ring(8)` is `640` on my system.
Shouldn't this be `8`?

cc @tkp1n

**Comment by tmds** [comment]
The value is calculated using:
```cs
        private static size_t SqSize(io_uring_params* p)
            =>  p->sq_off.array + p->sq_entries * sizeof(uint);
```
`p->sq_entries` is `8`.

**Comment by tkp1n** [comment]
Can reproduce it on my system. Will investigate...

**Comment by tkp1n** [comment]
Fixed the reported size of the sq and cq to be the number of elements instead of the number of `mmap`ed bytes.. Thank you for reporting this!

**Comment by tmds** [comment]
@tkp1n I think this bug made me try to add more request to the ring than what was possible, though `Ring.Prepare*` calls didn't throw for me. Maybe they should have thrown?
