### ISSUE TITLE
Ring.Prepare* doesn't throw as expected

### ISSUE THREAD

**Issue by tkp1n** [tkp1n/IoUring#24]
@tkp1n I think this bug made me try to add more request to the ring than what was possible, though `Ring.Prepare*` calls didn't throw for me. Maybe they should have thrown?

_Originally posted by @tmds in https://github.com/tkp1n/IoUring/issues/22#issuecomment-588131014_

**Comment by tkp1n** [comment]
Currently all Prepare* methods will silently submit and flush for you, if the sq is full to make room for the submission. 
I think I'll change this to a fail-fast approach that actually throws... what do you think @tmds?

https://github.com/tkp1n/IoUring/blob/d1a8513ec311b7ae6d68e2ae8b5c3d4578eb0725/src/IoUring/Ring.Submission.cs#L708-L716

There was also an off-by-one-bug which I fixed with d1a8513

**Comment by tmds** [comment]
> Currently all Prepare* methods will silently submit and flush for you

The `Prepare` prefix made me think they would not submit.
It makes sense to have a method that has the _flush+submit_ behavior when the queue is full.
