### ISSUE TITLE
Return EBUSY from io_uring_enter as a value instead of exception

### ISSUE THREAD

**Issue by tmds** [tkp1n/IoUring#27]
`io_uring_enter` can return `EBUSY` which means application must start reading completions before new submissions can be added. Currently this leads to `throw ErrnoException`. For performance it would be better this case can be detected without an exception.

cc @tkp1n

**Comment by tmds** [comment]
The same applies to `EAGAIN` and maybe some other `errno` returned by `io_uring_enter`.

**Comment by tkp1n** [comment]
I suggest making `Ring.Flush` return `bool` with the following semantics:
- `true`: `io_uring_enter` returned non-negative
- `false`: `io_uring_enter` returned -1 with errno `EAGAIN` or `EBUSY`
- Exception thrown: `io_uring_enter` returned -1 with some other errno

The number of I/O operations consumed by the kernel will be communicated via an additional  `out uint operationsFlushed` parameter.
